### ISSUE TITLE
[Error] SourceMap error, behaviors disabled in Eleventy

### ISSUE THREAD

**Issue by sethlbrown** [gregwolanski/eleventy-tailwindcss-alpinejs-starter#2]
First of all, thanks for your article on CSS Tricks and thanks for contributing an Eleventy Starter. I enjoyed walking through the process and I learned quite a bit walking through the code. 

I have a working CodePen that pulls in Alpine (2.4.1), Tailwind and TailwindUI. It works just fine and can be viewed here:

https://codepen.io/sethlbrown/pen/eYYqxQB or in debug mode if you want to see just the working version without codepen's UI: https://cdpn.io/sethlbrown/debug/eYYqxQB

When I try to include just the header that I wrote in my Eleventy build's default.njk, I'm able to view the page.

`npm run start` works without throwing any errors. However, all of the hover behaviors and the behaviors driven by Alpine.js no longer work in the Eleventy version. I'm able to see that the window.Alpine object exists and it's using version 2.4.1. It's the same version that the CodePen is using. Furthermore, I'm able to click through in the source and see that there's a minifed copy of Alpine.

There's was one Console error that seemed meaningful: 

```
Source map error: Error: request failed with status 404
Resource URL: http://localhost:8080/js/alpine.js?v=1594581372158
Source Map URL: alpine.js.map
```

I thought adding the following to my .eleventy.js file might help:

```
  eleventyConfig.addPassthroughCopy({
    "./node_modules/alpinejs/dist/alpine.js.map": "./js/alpine.js.map",
  });
```

It resolved the error but didn't get the behaviors on the site working.

I'm a rank beginner so I'm not clear from the docs what SourceMap has to do with getting Alpine to work in this context, but I wonder if there might be something missing in the provided .eleventy.js or postcss.config.js file? Again, not sure, but would appreciate your help.

I added my own tailwind.config.js file and that could also be the issue.

I [set up a repository](https://github.com/sethlbrown/wocbp-eatstack) in case you want to take a look. There are only two commits on top of the starter.

Thanks for any help you can provide.

**Comment by gregwolanski** [comment]
Hi Seth! : ) Thanks for writing. I appreciate it. 

The hover behaviors didn’t work because of my oversight. Fortunately, @tomhermans [noticed](https://css-tricks.com/eleventy-starter-with-tailwind-css-alpine-js/#comment-1760233) it (thanks Tom! : ). I already fixed it in the starter (https://github.com/gregwolanski/eleventy-tailwindcss-alpinejs-starter/commit/d3a9f89d34f3964d090fe1a3d1c100228f298210).

The behaviors driven by Alpine.js will start working when you remove my sample code from `index.jk`. `<div class="fixed inset-0 flex justify-center items-center">` is obscuring your code. You don’t have it in your code on CodePen – that's why your code works perfectly there.

I hope it helps.

Thank you for sharing the issues! : )
